// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdxuuenpwwqozxsiycdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1keHV1ZW5wd3dxb3p4c2l5Y2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjY5NDYsImV4cCI6MjA2MTM0Mjk0Nn0.zI8IFlWZ05p1GmUkph8jZJ8ZamqLP8NxjwhWaHZhAcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);